models/Tree.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tree".
 *
 * @property int $id
 * @property int $parent_id
 * @property int $position
 * @property string $path
 * @property int $level
 *
 * @property Tree $parent
 * @property Tree[] $children
 * @property Tree $leftChild
 * @property Tree $rightChild
 */
class Tree extends \yii\db\ActiveRecord
{
    const POS_LEFT = 1;
    const POS_RIGHT = 2;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tree';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['parent_id', 'position', 'level'], 'integer'],
            [['level'], 'required'],
            [['path'], 'string', 'max' => 12288],
            [['parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => Tree::class, 'targetAttribute' => ['parent_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'Parent ID',
            'position' => 'Position',
            'path' => 'Path',
            'level' => 'Level',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Tree::class, ['id' => 'parent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChildren()
    {
        return $this->hasMany(Tree::class, ['parent_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeftChild()
    {
        return $this->hasOne(Tree::class, ['parent_id' => 'id'])->where(['position' => 1]);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRightChild()
    {
        return $this->hasOne(Tree::class, ['parent_id' => 'id'])->where(['position' => 2]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Tree;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

class SiteController extends Controller
{
    /**
     * Displays homepage with tree.
     *
     * @return string
     */
    public function actionIndex()
    {
        $tree = Yii::$app->treeManager->treeCreator->getFirstNode();

        return $this->render('index', [
            'tree' => $tree
        ]);
    }

    /**
     * Displays tables data.
     *
     * @return string
     */
    public function actionTable()
    {
        $treeProvider = new ActiveDataProvider([
            'query' => Tree::find()
        ]);

        return $this->render('table', [
            'treeProvider' => $treeProvider
        ]);
    }

    /**
     * Clear tree
     *
     * @return \yii\web\Response
     */
    public function actionClearTree()
    {
      Yii::$app->treeManager->clearTree();

      return $this->redirect('index');
    }

    /**
     * Fill tree
     *
     * @return \yii\web\Response
     */
    public function actionFillTree()
    {
      Yii::$app->treeManager->fillTree();

      return $this->redirect('index');
    }

    /**
     * Create new tree node
     *
     * @param $parentId integer
     * @param $position integer
     * @return \yii\web\Response
     */
    public function actionAddNode($parentId, $position)
    {
        Yii::$app->treeManager->treeCreator->createNode($parentId, $position);

        return $this->redirect('index');
    }

    /**
     * Action for node moving
     *
     * @param $id
     * @param $parentId
     * @param $position
     * @return \yii\web\Response
     */
    public function actionMoveNode($id, $parentId, $position)
    {
        Yii::$app->treeManager->moveNode($id, $parentId, $position);

        return $this->redirect('index');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'View Tree', 'url' => ['/']],
            ['label' => 'Create new tree', 'url' => ['/site/fill-tree']],
            ['label' => 'Clear tree', 'url' => ['/site/clear-tree']],
            ['label' => 'View Table', 'url' => ['/site/table']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Inna Diachenko <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $tree app\models\Tree */

$this->title = Yii::$app->name;
?>
<div class="site-index">
    <div class="body-content">
        <div class="row">
            <h1>Model Tree Structure with Materialized Paths</h1>
            <div class="examples">
                <div class="example">
                    <div class="node-content head"></div>
                    <span class="tip"> - HEAD node</span>
                </div>
                <div class="example">
                    <div class="node-content left example"></div>
                    <span class="tip"> - LEFT node</span>
                </div>
                <div class="example">
                    <div class="node-content right example"></div>
                    <span class="tip"> - RIGHT node</span>
                </div>
            </div>
            <span>*You can move Blue and Rose nodes.</span>
            <hr/>
            <?= $this->render('node', ['node' => $tree]);?>
            <?= $this->render('tree', ['tree' => $tree]);?>
        </div>
    </div>
</div>

views/site/node.php
<?php

use app\models\Tree;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $node Tree */
/* @var $parentId integer */
/* @var $position integer */

$this->title = Yii::$app->name;
$nodeType = (empty($parentId) ? 'head' : ($position === Tree::POS_LEFT ? 'left item' : 'right item'));
?>
<div class="node-item">
    <?php if (!empty($node)) :?>
        <div class="<?= 'node-content ' . $nodeType ?>" data-id="<?= $node->id ?>">
            <div>
                <?= $node->id ?>
            </div>
        </div>
    <?php else:?>
        <div class="node-content new-node" data-id="<?= $parentId ?>" data-position="<?= $position ?>">
            <a href="<?= Url::to(['/site/add-node', 'parentId' => $parentId, 'position' => $position]) ?>">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
    <?php endif;?>
</div>

views/site/table.php
<?php

/* @var $this yii\web\View */
/* @var $treeProvider \yii\data\ActiveDataProvider */

$this->title = Yii::$app->name;
?>
<div class="site-index">
    <div class="body-content">
        <div class="row">
            <div class="col-lg-12">
                <?= \yii\grid\GridView::widget(['dataProvider' => $treeProvider]); ?>
            </div>
        </div>
    </div>
</div>

views/site/tree.php
<?php

use \app\models\Tree;

/* @var $this yii\web\View */
/* @var $tree \app\models\Tree */

$this->title = Yii::$app->name;
?>
<div class="tree">
    <div class="row">
        <div class="col-xs-6">
            <?= $this->render('node', [
                    'node' => $tree->leftChild,
                    'parentId' => $tree->id,
                    'position' => Tree::POS_LEFT
            ]) ?>
        </div>
        <div class="col-xs-6">
            <?= $this->render('node', [
                    'node' => $tree->rightChild,
                    'parentId' => $tree->id,
                    'position' => Tree::POS_RIGHT
                ]) ?>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-xs-6">
            <?= $tree->leftChild ? $this->render('tree', ['tree' => $tree->leftChild]) : ''; ?>
        </div>
        <div class="col-xs-6">
            <?= $tree->rightChild ? $this->render('tree', ['tree' => $tree->rightChild]) : '' ?>
        </div>
    </div>
</div>